### ISSUE TITLE
一个不相关的issue

### ISSUE THREAD

**Issue by wanqian-windrunner** [dongguaguaguagua/DoubanSpider#1]
很抱歉提了一个不相关的 issue ，想问一下 `fuck_chuanggao` 那个项目用的脱壳工具是什么，试了一些都不尽如人意

**Comment by zimya** [comment]
> 很提了一个不相关的 issue ，想问一下 `fuck_chuanggao` 那个项目用的脱壳工具是什么，试了一些都不尽如人意

[FunDex](https://github.com/Xposed-Modules-Repo/com.zhenxi.fundex2)，基于lsposed @wanqian-windrunner

**Comment by wanqian-windrunner** [comment]
okok，十分感谢
